### ISSUE TITLE
el auto no gira

### ISSUE THREAD

**Issue by rmarku** [UCC-ArquitecturaSoftwareI/primer-parcial-favaro-menel#2]
Solamente eso, no gira en la rama development. 
Recuerden que pueden usar la cámara de raylib para facilitar el diseño.

**Comment by AngeloMenel98** [comment]
sabemos que tenemos que usar esa funcion de raylib , solamente que estamos tratando de escribir primero el codigo de la carga del mapa, el jugador, y los otros autos.

**Comment by JCFavaro** [comment]
> Solamente eso, no gira en la rama development.
> Recuerden que pueden usar la cámara de raylib para facilitar el diseño.

Sí!, en realidad lo que subimos por ahora fueron pruebas, nos falta hasta escalar el mapa correctamente, queríamos centrarnos primero en esto, después en la funcionalidad y después hacer que gire correctamente.

**Comment by AngeloMenel98** [comment]
Se soluciono en el commit "Cambio en el movimiento de autos"

**Comment by rmarku** [comment]
Bien ahí, Tip para poner el comentario, podes poner directamente el hash del commit 824b23e1b94d470fe0bc11da213c42beef7d8e9e
Entonces decís, " Se solucionó en 824b23e1b94d470fe0bc11da213c42beef7d8e9e"

Al hash lo podes ver en el historial de commits de Github, y directamente esta el botoncito del portapapeles para copiarlo
